package com.eraine.delivery.persistence;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedUuid;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSortKey;

import java.time.Instant;

@Builder
@NoArgsConstructor
@AllArgsConstructor
@Data
@DynamoDbBean
public class RuleEntity {

    public static final String TABLE_NAME = "Rule";

    @Getter(onMethod_ = {@DynamoDbPartitionKey, @DynamoDbAutoGeneratedUuid} )
    private String id;

    @Getter(onMethod_ = @DynamoDbSortKey)
    private Integer priority;
    private String name;
    private String condition;
    private String costFormula;

    @Getter(onMethod_ = @DynamoDbAutoGeneratedTimestampAttribute)
    private Instant updatedTime;
}
