package com.eraine.delivery.config;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import software.amazon.awssdk.auth.credentials.AwsCredentialsProvider;
import software.amazon.awssdk.enhanced.dynamodb.DynamoDbEnhancedClient;
import software.amazon.awssdk.enhanced.dynamodb.extensions.AutoGeneratedTimestampRecordExtension;
import software.amazon.awssdk.regions.providers.AwsRegionProvider;
import software.amazon.awssdk.services.dynamodb.DynamoDbClient;

import java.net.URI;

@Configuration
public class DynamoDbConfig {

    private final String endpointUri;

    public DynamoDbConfig(@Value("${service.dynamodb.endpoint-uri}") String endpointUri) {
        this.endpointUri = endpointUri;
    }

    @Bean
    public DynamoDbClient dynamoDbClient(AwsRegionProvider region, AwsCredentialsProvider credentialsProvider) {
        return DynamoDbClient.builder()
                .region(region.getRegion())
                .credentialsProvider(credentialsProvider)
                .endpointOverride(URI.create(endpointUri))
                .build();
    }

    @Bean
    public DynamoDbEnhancedClient dynamoDbEnhancedClient(DynamoDbClient dynamoDbClient) {
        return DynamoDbEnhancedClient.builder()
                .dynamoDbClient(dynamoDbClient)
                .extensions(AutoGeneratedTimestampRecordExtension.create())
                .build();
    }
}
